name: NaturalSnowman
main: me.thenewtao.snowman.Snowman
version: 1.0
author: TheNewTao
commands:
  snowman:
    description: Allows you to modify snowgolem's name and rate of spawn.
    usage: /snowman and /snowman setname [name]
permissions:
  snowgolem.command:
    description: Allows you to do /snowgolem
    default: op